# Generated by Django 3.0.3 on 2020-03-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200107_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='niketestbackend',
            name='password',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='niketestbackend',
            name='size',
            field=models.FloatField(default='M 10.5', max_length=8),
        ),
        migrations.AddField(
            model_name='niketestbackend',
            name='username',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='niketestbackend',
            name='url',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
