# Generated by Django 3.0.3 on 2020-03-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200315_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niketestbackend',
            name='size',
            field=models.CharField(default='M 10.5', max_length=8),
        ),
    ]
