# Generated by Django 3.0.3 on 2020-03-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200315_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niketestbackend',
            name='size',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
